FROM ubuntu:latest

RUN apt-get update &&\
    apt-get install openjdk-8-jdk -y
RUN apt-get install wget -y


WORKDIR /usr/local
RUN wget http://apachemirror.wuchna.com/hbase/2.2.4/hbase-2.2.4-bin.tar.gz

RUN tar -zxvf hbase-2.2.4-bin.tar.gz && \
    rm hbase-2.2.4-bin.tar.gz

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV HBASE_HOME=/usr/local/hbase-2.2.4
ENV PATH=$PATH:$HBASE_HOME/bin

RUN sed -i '/^#.*10101/s/^#//;/^#.*10102/s/^#//;/^#.*authenticate=false/s/^#//'  hbase-2.2.4/conf/hbase-env.sh
RUN chmod 777 hbase-2.2.4/bin/start-hbase.sh
ENTRYPOINT ["start-hbase.sh"]