package com.appdynamics.monitors.hbase.lookup;

import java.util.HashMap;

public class MetricLookup {
	@SuppressWarnings("serial")
	private final static HashMap<String, String> metricLookup = new HashMap<String, String>() {{
		put("totalStaticBloomSizeKB", "Total Static Bloom Size (KB)");
		put("totalStaticIndexSizeKB", "Total Static Index Size (KB)");
		put("blockCacheFree", "Block Cache Free");
		put("compactionSizeNumOps", "Compaction Size Operations");
		put("compactionSizeAvgTime", "Compaction Size Avg Time");
		put("compactionSizeMinTime", "Compaction Size Min Time");
		put("compactionSizeMaxTime", "Compaction Size Max Time");
		put("numPutsWithoutWAL", "Num Puts Without Write-Ahead Logging");
		put("memstoreSizeMB", "Memstore Size (MB)");
		put("regions", "Regions");
		put("blockCacheCount", "Block Cache Count");
		put("blockCacheHitRatio", "Block Cache Hit Ratio");
		put("flushQueueSize", "Flush Queue Size");
		put("atomicIncrementTimeNumOps", "Atomic Increment Time Operations");
		put("atomicIncrementTimeAvgTime", "Atomic Increment Time Avg Time");
		put("atomicIncrementTimeMinTime", "Atomic Increment Time Min Time");
		put("atomicIncrementTimeMaxTime", "Atomic Increment Time Max Time");
		put("fsReadLatencyNumOps", "Filesystem Read Operations");
		put("fsReadLatencyAvgTime", "Filesystem Read Latency Avg Time");
		put("fsReadLatencyMinTime", "Filesystem Read Latency Min Time");
		put("fsReadLatencyMaxTime", "Filesystem Read Latency Max Time");
		put("blockCacheHitCachingRatio", "Block Cache Hit Caching Ratio");
		put("blockCacheHitCount", "Block Cache Hit Count");
		put("hdfsBlocksLocalityIndex", "HDFS Blocks Locality Index");
		put("mbInMemoryWithoutWAL", "Memory Without WAL (MB)");
		put("writeRequestsCount", "Write Requests Count");
		put("slowHLogAppendTimeNumOps", "Slow H-Log Append Operations");
		put("slowHLogAppendTimeAvgTime", "Slow H-Log Append Time Avg Time");
		put("slowHLogAppendTimeMinTime", "Slow H-Log Append Time Min Time");
		put("slowHLogAppendTimeMaxTime", "Slow H-Log Append Time Max Time");
		put("compactionTimeNumOps", "Compaction Operations");
		put("compactionTimeAvgTime", "Compaction Time Avg Time");
		put("compactionTimeMinTime", "Compaction Time Min Time");
		put("compactionTimeMaxTime", "Compaction Time Max Time");
		put("fsWriteLatencyNumOps", "Filesystem Write Latency Operations");
		put("fsWriteLatencyAvgTime", "Filesystem Write Latency Avg Time");
		put("fsWriteLatencyMinTime", "Filesystem Write Latency Min Time");
		put("fsWriteLatencyMaxTime", "Filesystem Write Latency Max Time");
		put("blockCacheSize", "Block Cache Size");
		put("readRequestsCount", "Read Requests Count");
		put("rootIndexSizeKB", "Root Index Size (KB)");
		put("blockCacheHitRatioPastNPeriods", "Block Cache Hit Ratio Past N-Periods");
		put("fsPreadLatencyNumOps", "Filesystem P-Read Latency Operations");
		put("fsPreadLatencyAvgTime", "Filesystem P-Read Latency Avg Time");
		put("fsPreadLatencyMinTime", "Filesystem P-Read Latency Min Time");
		put("fsPreadLatencyMaxTime", "Filesystem P-Read Latency Max Time");
		put("flushTimeNumOps", "Flush Time Operations");
		put("flushTimeAvgTime", "Flush Time Avg Time");
		put("flushTimeMinTime", "Flush Time Min Time");
		put("flushTimeMaxTime", "Flush Time Max Time");
		put("checksumFailuresCount", "Checksum Failures Count");
		put("blockCacheMissCount", "Block Cache Miss Count");
		put("blockCacheHitCachingRatioPastNPeriods", "Block Cache Hit Caching Ratio Past N-Periods");
		put("slowHLogAppendCount", "Slow H-Log Append Count");
		put("fsWriteSizeNumOps", "Filesystem Write Size Operations");
		put("fsWriteSizeAvgTime", "Filesystem Write Size Avg Time");
		put("fsWriteSizeMinTime", "Filesystem Write Size Min Time");
		put("fsWriteSizeMaxTime", "Filesystem Write Size Max Time");
		put("storefiles", "Storefiles");
		put("regionSplitFailureCount", "Region Split Failure Count");
		put("blockCacheEvictedCount", "Block Cache Evicted Count");
		put("storefileIndexSizeMB", "Storefile Index Size (MB)");
		put("fsSyncLatencyNumOps", "Filesystem Sync Latency Operations");
		put("fsSyncLatencyAvgTime", "Filesystem Sync Latency Avg Time");
		put("fsSyncLatencyMinTime", "Filesystem Sync Latency Min Time");
		put("fsSyncLatencyMaxTime", "Filesystem Sync Latency Max Time");
		put("stores", "Stores");
		put("compactionQueueSize", "Compaction Queue Size");
		put("flushSizeNumOps", "Flush Size Operations");
		put("flushSizeAvgTime", "Flush Size Avg Time");
		put("flushSizeMinTime", "Flush Size Min Time");
		put("flushSizeMaxTime", "Flush Size Max Time");
		put("regionSplitSuccessCount", "Region Split Success Count");
		put("fsWriteLatencyHistogram_num_ops", "Filesystem Write Latency Histogram Operations");
		put("fsWriteLatencyHistogram_min", "Filesystem Write Latency Histogram Min");
		put("fsWriteLatencyHistogram_max", "Filesystem Write Latency Histogram Max");
		put("fsWriteLatencyHistogram_mean", "Filesystem Write Latency Histogram Mean");
		put("fsWriteLatencyHistogram_std_dev", "Filesystem Write Latency Histogram Standard Deviation");
		put("fsWriteLatencyHistogram_median", "Filesystem Write Latency Histogram Median");
		put("fsWriteLatencyHistogram_75th_percentile", "Filesystem Write Latency Histogram 75th percentile");
		put("fsWriteLatencyHistogram_95th_percentile", "Filesystem Write Latency Histogram 95th percentile");
		put("fsWriteLatencyHistogram_99th_percentile", "Filesystem Write Latency Histogram 99th percentile");
		put("requests", "Requests");
		put("fsPreadLatencyHistogram_num_ops", "Filesystem Pread Latency Histogram Operations");
		put("fsPreadLatencyHistogram_min", "Filesystem Pread Latency Histogram Min");
		put("fsPreadLatencyHistogram_max", "Filesystem Pread Latency Histogram Max");
		put("fsPreadLatencyHistogram_mean", "Filesystem Pread Latency Histogram Mean");
		put("fsPreadLatencyHistogram_std_dev", "Filesystem Pread Latency Histogram Standard Deviation");
		put("fsPreadLatencyHistogram_median", "Filesystem Pread Latency Histogram Median");
		put("fsPreadLatencyHistogram_75th_percentile", "Filesystem Pread Latency Histogram 75th percentile");
		put("fsPreadLatencyHistogram_95th_percentile", "Filesystem Pread Latency Histogram 95th percentile");
		put("fsPreadLatencyHistogram_99th_percentile", "Filesystem Pread Latency Histogram 99th percentile");
		put("fsReadLatencyHistogram_num_ops", "Filesystem Read Latency Histogram Operations");
		put("fsReadLatencyHistogram_min", "Filesystem Read Latency Histogram Min");
		put("fsReadLatencyHistogram_max", "Filesystem Read Latency Histogram Max");
		put("fsReadLatencyHistogram_mean", "Filesystem Read Latency Histogram Mean");
		put("fsReadLatencyHistogram_std_dev", "Filesystem Read Latency Histogram Standard Deviation");
		put("fsReadLatencyHistogram_median", "Filesystem Read Latency Histogram Median");
		put("fsReadLatencyHistogram_75th_percentile", "Filesystem Read Latency Histogram 75th percentile");
		put("fsReadLatencyHistogram_95th_percentile", "Filesystem Read Latency Histogram 95th percentile");
		put("fsReadLatencyHistogram_99th_percentile", "Filesystem Read Latency Histogram 99th percentile");
		put("updatesBlockedSeconds_num_ops", "Updates Blocked Seconds Operations");
		put("updatesBlockedSeconds_min", "Updates Blocked Seconds Min");
		put("updatesBlockedSeconds_max", "Updates Blocked Seconds Max");
		put("updatesBlockedSeconds_mean", "Updates Blocked Seconds Mean");
		put("updatesBlockedSeconds_std_dev", "Updates Blocked Seconds Standard Deviation");
		put("updatesBlockedSeconds_median", "Updates Blocked Seconds Median");
		put("updatesBlockedSeconds_75th_percentile", "Updates Blocked Seconds 75th percentile");
		put("updatesBlockedSeconds_95th_percentile", "Updates Blocked Seconds 95th percentile");
		put("updatesBlockedSeconds_99th_percentile", "Updates Blocked Seconds 99th percentile");
		put("updatesBlockedSecondsHighWater_num_ops", "Updates Blocked Seconds High Water Operations");
		put("updatesBlockedSecondsHighWater_min", "Updates Blocked Seconds High Water Min");
		put("updatesBlockedSecondsHighWater_max", "Updates Blocked Seconds High Water Max");
		put("updatesBlockedSecondsHighWater_mean", "Updates Blocked Seconds High Water Mean");
		put("updatesBlockedSecondsHighWater_std_dev", "Updates Blocked Seconds High Water Standard Deviation");
		put("updatesBlockedSecondsHighWater_median", "Updates Blocked Seconds High Water Median");
		put("updatesBlockedSecondsHighWater_75th_percentile", "Updates Blocked Seconds High Water 75th percentile");
		put("updatesBlockedSecondsHighWater_95th_percentile", "Updates Blocked Seconds High Water 95th percentile");
		put("updatesBlockedSecondsHighWater_99th_percentile", "Updates Blocked Seconds High Water 99th percentile");
	}};

	public static String getMetric(String metricName) {
		return metricLookup.get(metricName);
	}
}
